services:
  - type: web
    name: domain-redirector
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: MONGODB_URI
        value: mongodb+srv://panzer:Aa563214aa%2E@cluster0.yacqmwk.mongodb.net/domain_manager?retryWrites=true&w=majority&appName=Cluster0
    healthCheckPath: /ping 