services:
  - type: web
    name: domain-redirector
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: MONGODB_URI
        value: mongodb://atlas-sql-67eb72a77706f91cc1fe19ce-ws9cn.a.query.mongodb.net/domain_manager?ssl=true&authSource=admin
    healthCheckPath: /ping 