services:
  - type: web
    name: domain-switcher-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
  - type: web
    name: domain-switcher-frontend
    env: static
    buildCommand: null
    staticPublishPath: ./frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 